<?php

namespace Sdz\BlogBundle\Entity;

/**
 * InterfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterfaceRepository extends \Doctrine\ORM\EntityRepository
{
}
