demo:
    resource: "@DemoBundle/Resources/config/routing.yml"
    prefix:   /acme

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

catalogue:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /catalogue

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
