blog_homepage:
    path:     /hello
    defaults: { _controller: BlogBundle:Default:index }
blog_accueil:
    path:     /{page}
    defaults: { _controller: BlogBundle:Blog:index, page: 1 }
    requirements:
        id: \d*
blog_ajouter:
    path:     /article/ajouter
    defaults: { _controller: BlogBundle:Blog:ajouter }
blog_voir:
    path:     /article/{id}
    defaults: { _controller: BlogBundle:Blog:voir }
    requirements:
        id: \d+
blog_modifier:
    path:     /modifier/{id}
    defaults: { _controller: BlogBundle:Blog:modifier }
    requirements:
        id: \d+
blog_supprimer:
    path:     /article/supprimer/{id}
    defaults: { _controller: BlogBundle:Blog:supprimer }
    requirements:
        id: \d+
blog_menu:
    path:     /article/menu
    defaults: { _controller: BlogBundle:Blog:menu }

blog_template:
    path:     /article/template
    defaults: { _controller: BlogBundle:Blog:template }

blog_test:
    path:     /test
    defaults: { _controller: BlogBundle:Test:test }

blog_name:
    path:     /name/
    defaults: { _controller: BlogBundle:Blog:exo }

blog_catalogue:
    path:     /produits/
    defaults: { _controller: BlogBundle:Catalogue:produits }

blog_catalogueMenu:
    path:     /produits/menu
    defaults: { _controller: BlogBundle:Catalogue:menu }

blog_cataloguePrestation:
    path:     /produits/presentation/{id}
    defaults: { _controller: BlogBundle:Catalogue:presentation }

blog_catalogueCategories:
    path:     /produits/categories/{id}
    defaults: { _controller: BlogBundle:Catalogue:categories }

blog_produitvoir:
    path:     /produits/voir/{id}
    defaults: { _controller: BlogBundle:Catalogue:voir }

blog_produitCreer:
    path:     /produits/creer
    defaults: { _controller: BlogBundle:Catalogue:creer }